import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { normalizeNumericInput } from '../../shared/input';
import type { AttendanceDayDto, AttendanceShiftDto, BackupItemDto, BackupStatusDto, CalculationMethod, CorrectionDetailDto, CorrectionInput, CorrectionListItemDto, CorrectionPreviewDto, EmployeeDto, MonthlyEmployeeDetailDto, MonthlySummaryDto, PayBreakdownDto, PwaAttendanceApi } from '../pwa-api.types';
import { Empty, Loading } from '../App';
import { Dialog } from './Dialog';

type Tab = '勤怠' | '従業員' | '月次' | '設定';
type Notice = { kind: 'success' | 'error'; text: string };
const rid = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const unwrap = async <T,>(promise: Promise<{ ok: true; data: T } | { ok: false; message: string }>) => { const result = await promise; if (!result.ok) throw new Error(result.message); return result.data; };
const monthNow = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo', year: 'numeric', month: '2-digit' }).format(new Date()).slice(0, 7);
const dateNow = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Tokyo' }).format(new Date());
const moveMonth = (month: string, delta: number) => { const [year, value] = month.split('-').map(Number); const next = new Date(year, value - 1 + delta, 1); return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`; };
const yen = (value: number) => `${value.toLocaleString('ja-JP')}円`;
const hm = (value: number | null) => value == null ? '勤務中' : new Date(value).toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' });

export function AdminApp({ api, onLock }: { api: PwaAttendanceApi; onLock: () => void }) {
  const [tab, setTab] = useState<Tab>('勤怠');
  const [notice, setNotice] = useState<Notice>();
  useEffect(() => { if (notice?.kind !== 'success') return; const timer = window.setTimeout(() => setNotice(current => current === notice ? undefined : current), 3000); return () => window.clearTimeout(timer); }, [notice]);
  return <section className="admin-page"><header className="admin-head"><div><p className="eyebrow">管理者</p><h1>{tab}</h1></div><button className="quiet-button" onClick={onLock}>ロックして打刻へ戻る</button></header>{notice && <p className={`inline-notice ${notice.kind}`} role="status">{notice.text}</p>}<div className="admin-content">{tab === '勤怠' && <AttendanceTab api={api} notify={setNotice} />}{tab === '従業員' && <EmployeesTab api={api} notify={setNotice} />}{tab === '月次' && <MonthlyTab api={api} notify={setNotice} />}{tab === '設定' && <SettingsTab api={api} notify={setNotice} />}</div><nav className="bottom-tabs" aria-label="管理メニュー">{(['勤怠', '従業員', '月次', '設定'] as Tab[]).map(item => <button key={item} aria-current={tab === item ? 'page' : undefined} onClick={() => setTab(item)}>{item}</button>)}</nav></section>;
}

function AttendanceTab({ api }: { api: PwaAttendanceApi; notify: (value: Notice) => void }) {
  const [month, setMonth] = useState(monthNow()); const [selected, setSelected] = useState(dateNow()); const [dates, setDates] = useState<string[]>([]); const [day, setDay] = useState<AttendanceDayDto>(); const [detail, setDetail] = useState<AttendanceShiftDto>(); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [calendar, dayData] = await Promise.all([unwrap(api.attendance.calendar(month)), unwrap(api.attendance.day(selected))]); setDates(calendar.attendanceDates); setDay(dayData); } catch (cause) { setError(cause instanceof Error ? cause.message : '勤怠を読み込めませんでした。'); } finally { setLoading(false); } }, [api, month, selected]);
  useEffect(() => { void load(); }, [load]);
  const days = useMemo(() => { const [y, m] = month.split('-').map(Number); const first = new Date(y, m - 1, 1).getDay(); const count = new Date(y, m, 0).getDate(); return [...Array(first).fill(null), ...Array.from({ length: count }, (_, i) => `${month}-${String(i + 1).padStart(2, '0')}`)]; }, [month]);
  return <><MonthBar month={month} setMonth={value => { setMonth(value); setSelected(`${value}-01`); }} /><div className="calendar" aria-label={`${month}の勤怠カレンダー`}><div className="weekdays">{['日','月','火','水','木','金','土'].map(value => <span key={value}>{value}</span>)}</div><div className="calendar-grid">{days.map((date, index) => date ? <button key={date} className={`${date === selected ? 'selected' : ''} ${date === dateNow() ? 'today-cell' : ''}`} aria-pressed={date === selected} onClick={() => setSelected(date)}><span>{Number(date.slice(-2))}</span>{date === dateNow() && <small>今日</small>}{dates.includes(date) && <i aria-label="記録あり" />}</button> : <span key={`blank-${index}`} />)}</div></div>{error ? <ErrorState text={error} retry={load} /> : loading ? <Loading /> : !day?.shifts.length ? <Empty title="この日の勤務記録はありません" /> : <><div className="day-summary"><strong>{new Date(`${selected}T00:00:00`).toLocaleDateString('ja-JP', { month: 'long', day: 'numeric', weekday: 'short' })}</strong><span>出勤 {day.totals.attendanceCount}回</span><span>確定済み {day.totals.totalMinutes}分・{yen(day.totals.totalYen)}</span><span>勤務中 {day.totals.openCount}件・要確認 {day.totals.reviewCount}件</span></div><div className="card-list">{day.shifts.map(shift => <button className="shift-card" key={shift.id} onClick={() => setDetail(shift)}><strong>{shift.employeeName}{shift.occurrenceOfDay > 1 && <small> 同日{shift.occurrenceOfDay}回目</small>}</strong><span>{hm(shift.effectiveClockIn)}〜{hm(shift.effectiveClockOut)}</span><em>{shift.state === 'OPEN' ? '勤務中' : shift.state === 'NEEDS_REVIEW' ? '要確認' : shift.pay ? yen(shift.pay.totalYen) : '除外'}</em></button>)}</div></>}{detail && <Dialog title="勤務詳細" onClose={() => setDetail(undefined)}><dl className="detail-list"><div><dt>従業員</dt><dd>{detail.employeeName}</dd></div><div><dt>出勤</dt><dd>{new Date(detail.effectiveClockIn).toLocaleString('ja-JP')}</dd></div><div><dt>退勤</dt><dd>{detail.effectiveClockOut ? new Date(detail.effectiveClockOut).toLocaleString('ja-JP') : '勤務中'}</dd></div><div><dt>通常時間</dt><dd>{detail.pay ? `${detail.pay.regularMinutes}分` : '集計対象外'}</dd></div><div><dt>深夜時間</dt><dd>{detail.pay ? `${detail.pay.nightMinutes}分` : '集計対象外'}</dd></div><div><dt>通常分</dt><dd>{detail.pay ? yen(detail.pay.regularYen) : '—'}</dd></div><div><dt>深夜分</dt><dd>{detail.pay ? yen(detail.pay.nightYen) : '—'}</dd></div><div><dt>合計</dt><dd>{detail.pay ? `${detail.pay.totalMinutes}分・${yen(detail.pay.totalYen)}` : '—'}</dd></div></dl></Dialog>}</>;
}

function EmployeesTab({ api, notify }: { api: PwaAttendanceApi; notify: (value: Notice) => void }) {
  const [rows, setRows] = useState<EmployeeDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<EmployeeDto | 'new'>(); const [archive, setArchive] = useState<EmployeeDto>();
  const load = useCallback(async () => { setLoading(true); try { setRows((await unwrap(api.employees.list(true))).sort((a,b) => a.name.localeCompare(b.name, 'ja'))); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : '従業員を読み込めませんでした。'); } finally { setLoading(false); } }, [api]); useEffect(() => { void load(); }, [load]);
  const restore = async (employee: EmployeeDto) => { try { await unwrap(api.employees.restore({ id: employee.id, requestId: rid() })); notify({ kind: 'success', text: `${employee.name}さんを復元しました。` }); await load(); } catch (cause) { notify({ kind: 'error', text: cause instanceof Error ? cause.message : '復元できませんでした。' }); } };
  const active = rows.filter(row => row.status === 'ACTIVE'), archived = rows.filter(row => row.status === 'ARCHIVED');
  return <><button className="primary full-button" onClick={() => setEditing('new')}>従業員を追加</button>{error ? <ErrorState text={error} retry={load} /> : loading ? <Loading /> : <>{[['在籍', active], ['削除済み', archived]].map(([title, values]) => <section className="employee-section" key={title as string}><h2>{title as string}</h2>{(values as EmployeeDto[]).length ? <div className="card-list">{(values as EmployeeDto[]).map(employee => <article className="employee-row" key={employee.id}><div><strong>{employee.name}</strong><span>時給 {yen(employee.hourlyWage)}</span>{employee.restoreUntil && <small>復元期限 {new Date(employee.restoreUntil).toLocaleDateString('ja-JP')}</small>}</div><div>{employee.status === 'ACTIVE' ? <><button onClick={() => setEditing(employee)}>編集</button><button className="danger-text" onClick={() => setArchive(employee)}>削除</button></> : <button onClick={() => void restore(employee)}>復元</button>}</div></article>)}</div> : <Empty title={`${title}の従業員はいません`} />}</section>)}</>}{editing && <EmployeeEditor employee={editing === 'new' ? undefined : editing} api={api} close={() => setEditing(undefined)} saved={async text => { setEditing(undefined); if (text) notify({ kind: 'success', text }); await load(); }} />}{archive && <Dialog title={`${archive.name}さんを削除しますか？`} closeLabel="キャンセル" onClose={() => setArchive(undefined)} actions={<button className="danger-button" onClick={async () => { try { await unwrap(api.employees.archive({ id: archive.id, requestId: rid() })); setArchive(undefined); notify({ kind: 'success', text: '削除済みに移動しました。30日間は復元できます。' }); await load(); } catch (cause) { notify({ kind: 'error', text: cause instanceof Error ? cause.message : '削除できませんでした。' }); } }}>削除する</button>}><p>勤務履歴は削除されません。30日間は「削除済み」から復元できます。</p></Dialog>}</>;
}

function EmployeeEditor({ employee, api, close, saved }: { employee?: EmployeeDto; api: PwaAttendanceApi; close: () => void; saved: (text: string) => Promise<void> }) { const [name, setName] = useState(employee?.name ?? ''); const [wage, setWage] = useState(String(employee?.hourlyWage ?? '')); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); const value = Number(wage); if (!name.trim() || !Number.isFinite(value) || value <= 0) return setError('氏名と正しい時給を入力してください。'); try { if (employee) await unwrap(api.employees.update({ id: employee.id, name: name.trim(), hourlyWage: value, requestId: rid() })); else await unwrap(api.employees.create({ name: name.trim(), hourlyWage: value, requestId: rid() })); await saved(employee ? '従業員情報と今後の時給を変更しました。' : ''); } catch (cause) { setError(cause instanceof Error ? cause.message : '保存できませんでした。'); } }; return <Dialog title={employee ? '従業員を編集' : '従業員を追加'} onClose={close} actions={<button type="submit" className="primary" form="employee-form">保存</button>}><form id="employee-form" className="stack-form" onSubmit={submit}><label>氏名<input autoFocus maxLength={80} value={name} onChange={event => setName(event.target.value)} /></label><label>時給（円）<input inputMode="numeric" value={wage} onChange={event => setWage(event.target.value.replace(/[^0-9０-９]/g, '').normalize('NFKC'))} /></label><p className="form-hint">時給の変更は今後の勤務に適用します。過去の時給スナップショットは変わりません。</p>{error && <p className="form-error" role="alert">{error}</p>}</form></Dialog>; }

function MonthlyTab({ api, notify }: { api: PwaAttendanceApi; notify: (value: Notice) => void }) {
  const [month, setMonth] = useState(monthNow()); const [summary, setSummary] = useState<MonthlySummaryDto>(); const [detail, setDetail] = useState<MonthlyEmployeeDetailDto>(); const [printDetails,setPrintDetails]=useState<MonthlyEmployeeDetailDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [confirm, setConfirm] = useState<'close'|'reopen'>(); const scroll = useState({ value: 0 })[0];
  const load = useCallback(async () => { setLoading(true); try { setSummary(await unwrap(api.monthly.summary(month))); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : '月次を読み込めませんでした。'); } finally { setLoading(false); } }, [api, month]); useEffect(() => { void load(); }, [load]);
  const openDetail = async (employeeId: string) => { scroll.value = window.scrollY; try { setDetail(await unwrap(api.monthly.employeeDetail(month, employeeId))); window.scrollTo(0, 0); } catch (cause) { notify({ kind: 'error', text: cause instanceof Error ? cause.message : '詳細を開けませんでした。' }); } };
  const closeDetail = () => { setDetail(undefined); requestAnimationFrame(() => window.scrollTo(0, scroll.value)); };
  const execute = async () => { if (!confirm) return; try { const data = confirm === 'close' ? await unwrap(api.monthly.close({ month, requestId: rid() })) : await unwrap(api.monthly.reopen({ month, requestId: rid() })); setSummary(data); notify({ kind: 'success', text: confirm === 'close' ? '月次を確定しました。' : '月次の確定を取り消しました。' }); } catch (cause) { notify({ kind: 'error', text: cause instanceof Error ? cause.message : '操作できませんでした。' }); } finally { setConfirm(undefined); } };
  const save = async () => { try { const data = await unwrap(api.monthly.exportCsv(month)); const url = URL.createObjectURL(new Blob([data.csv], { type: data.mimeType })); const a = document.createElement('a'); a.href=url; a.download=data.fileName; a.click(); URL.revokeObjectURL(url); } catch (cause) { notify({ kind: 'error', text: cause instanceof Error ? cause.message : '保存できませんでした。' }); } };
  const printAll=async()=>{if(!summary)return;try{await unwrap(api.monthly.print(month));const details=await Promise.all(summary.employees.map(employee=>unwrap(api.monthly.employeeDetail(month,employee.employeeId))));setPrintDetails(details);requestAnimationFrame(()=>requestAnimationFrame(()=>{window.print();setPrintDetails([]);}));}catch(cause){notify({kind:'error',text:cause instanceof Error?cause.message:'印刷できませんでした。'});}};
  if (detail) return <section className="detail-screen"><button className="back" onClick={closeDetail}>‹ 月次一覧へ戻る</button><h2>{detail.employee.name}</h2><div className="summary-card"><span>{detail.month}・{detail.totals.attendanceCount}回</span><PayBreakdownRows pay={detail.totals}/></div>{detail.days.map(day => <article className="monthly-day-detail" key={day.date}><strong>{new Date(`${day.date}T00:00`).toLocaleDateString('ja-JP', { month:'numeric', day:'numeric', weekday:'short' })}</strong><PayBreakdownRows pay={day.totals}/></article>)}<p className="salary-note">※残業・休日割増は含まれていません</p></section>;
  return <><MonthBar month={month} setMonth={setMonth} />{error ? <ErrorState text={error} retry={load} /> : loading ? <Loading /> : summary && <><div className="summary-card"><span>{summary.status === 'CLOSED' ? '確定済み' : '未確定'}</span><strong>{yen(summary.totalYen)}</strong><small>{summary.totalMinutes}分・{summary.attendanceCount}回</small><small>勤務中 {summary.openCount}件・要確認 {summary.reviewCount}件・旧承認待ち {summary.legacyPendingCount}件</small></div><div className="monthly-actions"><button disabled={summary.status === 'OPEN' && !summary.canClose} onClick={() => setConfirm(summary.status === 'CLOSED' ? 'reopen' : 'close')}>{summary.status === 'CLOSED' ? '確定を取り消す' : '月次を確定'}</button><details><summary>保存・印刷</summary><button onClick={() => void save()}>Excel用データを保存</button><button onClick={() => void printAll()}>印刷</button></details></div>{!summary.employees.length ? <Empty title="この月の集計はありません" /> : <div className="card-list">{summary.employees.map(employee => <button className="monthly-row" key={employee.employeeId} onClick={() => void openDetail(employee.employeeId)}><strong>{employee.employeeName}</strong><span>{employee.totalMinutes}分・{employee.attendanceCount}回</span><b>{yen(employee.totalYen)}</b></button>)}</div>}<p className="salary-note">※残業・休日割増は含まれていません</p></>}{confirm && <Dialog title={confirm === 'close' ? `${month}を確定しますか？` : `${month}の確定を取り消しますか？`} onClose={() => setConfirm(undefined)} closeLabel="キャンセル" actions={<button className="primary" onClick={() => void execute()}>{confirm === 'close' ? '確定する' : '確定を取り消す'}</button>}><p>{confirm === 'close' ? '勤務中・要確認・旧承認待ちがある場合は確定できません。' : '編集と訂正が再び可能になります。'}</p></Dialog>}{summary&&printDetails.length>0&&<PrintReport summary={summary} details={printDetails}/>}</>;
}

function PayBreakdownRows({ pay }: { pay: PayBreakdownDto }) { return <dl className="pay-breakdown"><div><dt>通常</dt><dd>{pay.regularMinutes}分・{yen(pay.regularYen)}</dd></div><div><dt>深夜</dt><dd>{pay.nightMinutes}分・{yen(pay.nightYen)}</dd></div><div><dt>合計</dt><dd>{pay.totalMinutes}分・{yen(pay.totalYen)}</dd></div></dl>; }
function PrintReport({summary,details}:{summary:MonthlySummaryDto;details:MonthlyEmployeeDetailDto[]}){return <section className="print-report"><h1>{summary.month} 月次給与見込み</h1><PayBreakdownRows pay={summary}/><p>出勤 {summary.attendanceCount}回・勤務中 {summary.openCount}件・要確認 {summary.reviewCount}件・旧承認待ち {summary.legacyPendingCount}件</p>{details.map(detail=><section key={detail.employee.id}><h2>{detail.employee.name}</h2><PayBreakdownRows pay={detail.totals}/>{detail.days.map(day=><article key={day.date}><strong>{day.date}</strong><PayBreakdownRows pay={day.totals}/></article>)}</section>)}<p>※残業・休日割増は含まれていません</p></section>}

function SettingsTab({ api, notify }: { api: PwaAttendanceApi; notify: (value: Notice) => void }) { const [screen, setScreen] = useState<'top'|'pin'|'backup'|'correction'>('top'); if (screen === 'top') return <div className="settings-list">{[['pin','管理者PINの変更','現在のPINを確認して変更します'],['backup','バックアップ','端末内の保存と復元を管理します'],['correction','出勤訂正','従業員と勤務を選び訂正します']].map(([id,title,text]) => <button key={id} onClick={() => setScreen(id as typeof screen)}><strong>{title}</strong><span>{text}</span></button>)}</div>; return <section><button className="back" onClick={() => setScreen('top')}>‹ 設定へ戻る</button>{screen === 'pin' && <PinChange api={api} notify={notify} />}{screen === 'backup' && <BackupPanel api={api} notify={notify} />}{screen === 'correction' && <CorrectionPanel api={api} notify={notify} />}</section>; }
function PinChange({ api, notify }: { api: PwaAttendanceApi; notify: (value: Notice) => void }) { const [oldPin,setOld]=useState(''); const [next,setNext]=useState(''); const [confirmation,setConfirmation]=useState(''); const [error,setError]=useState(''); const submit=async(e:FormEvent)=>{e.preventDefault();if(oldPin.length!==6||next.length!==6)return setError('現在と新しいPINを6桁で入力してください。');if(next!==confirmation)return setError('新しいPINと確認入力が一致しません。');setError('');try{await unwrap(api.adminAuth.changePin({oldPin,newPin:next,requestId:rid()}));notify({kind:'success',text:'管理者PINを変更しました。'});setOld('');setNext('');setConfirmation('');}catch(cause){setError(cause instanceof Error?cause.message:'変更できませんでした。');}}; const pin=(value:string,set:(value:string)=>void)=><input type="password" inputMode="numeric" pattern="[0-9０-９]*" maxLength={6} value={value} onChange={e=>set(normalizeNumericInput(e.target.value,6))}/>; return <form className="stack-form" onSubmit={submit}><h2>管理者PINの変更</h2><label>現在のPIN{pin(oldPin,setOld)}</label><label>新しいPIN{pin(next,setNext)}</label><label>新しいPIN（確認）{pin(confirmation,setConfirmation)}</label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary">変更する</button></form>; }
function BackupPanel({ api, notify }: { api:PwaAttendanceApi;notify:(value:Notice)=>void }) { const [items,setItems]=useState<BackupItemDto[]>([]); const [status,setStatus]=useState<BackupStatusDto>(); const [restore,setRestore]=useState<BackupItemDto>(); const load=useCallback(async()=>{try{const [list,current]=await Promise.all([unwrap(api.backup.list()),unwrap(api.backup.status())]);setItems(list);setStatus(current);}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'読み込めませんでした。'});}},[api,notify]); useEffect(()=>{void load();},[load]); const execute=async()=>{if(!restore)return;try{await unwrap(api.backup.restore({id:restore.id,requestId:rid()}));location.reload();}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'復元できませんでした。'});setRestore(undefined);}}; const saveFile=async(item:BackupItemDto)=>{try{const data=await unwrap(api.backup.export(item.id));const url=URL.createObjectURL(new Blob([data.json],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=data.fileName;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'ファイルへ保存できませんでした。'});}}; return <><h2>バックアップ</h2><p className="form-hint">同一端末・同一オリジン内の保存です。端末故障やストレージ消去への完全な保護ではありません。</p>{status&&<dl className="backup-status"><div><dt>永続化</dt><dd>{status.persisted===true?'有効':status.persisted===false?'無効':'確認できません'}</dd></div><div><dt>使用量 / 容量</dt><dd>{bytes(status.usage)} / {bytes(status.quota)}</dd></div><div><dt>最終成功</dt><dd>{status.lastSuccessAt?new Date(status.lastSuccessAt).toLocaleString('ja-JP'):'—'}</dd></div><div><dt>最終失敗</dt><dd>{status.lastFailureAt?new Date(status.lastFailureAt).toLocaleString('ja-JP'):'—'}{status.lastFailure&&`（${status.lastFailure}）`}</dd></div></dl>}<button className="primary full-button" onClick={async()=>{try{await unwrap(api.backup.create({kind:'MANUAL',requestId:rid()}));await load();}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'作成できませんでした。'});}}}>手動バックアップを作成</button><div className="card-list">{items.map(item=><article className="employee-row" key={item.id}><div><strong>{item.fileName}</strong><span>{new Date(item.createdAt).toLocaleString('ja-JP')}</span></div><div><button onClick={()=>void saveFile(item)}>ファイルへ保存</button><button onClick={()=>setRestore(item)}>復元</button></div></article>)}</div>{restore&&<Dialog title="バックアップから復元しますか？" closeLabel="キャンセル" onClose={()=>setRestore(undefined)} actions={<button className="danger-button" onClick={()=>void execute()}>復元する</button>}><p><strong>{restore.fileName}</strong> の内容で現在の勤怠・従業員・月次データを置き換えます。</p><p>現在の管理者PINと回復コードは変更されません。復元成功後はセッションを終了し、管理者PINでの再認証が必要です。</p></Dialog>}</>; }
function bytes(value:number|null){if(value==null)return '—';if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`;}
function CorrectionPanel({ api, notify }: { api:PwaAttendanceApi;notify:(value:Notice)=>void }) {
  const [employees,setEmployees]=useState<EmployeeDto[]>([]); const [employee,setEmployee]=useState(''); const [shifts,setShifts]=useState<CorrectionListItemDto[]>([]); const [detail,setDetail]=useState<CorrectionDetailDto>(); const [preview,setPreview]=useState<CorrectionPreviewDto>(); const [input,setInput]=useState<CorrectionInput>(); const [legacyAction,setLegacyAction]=useState<'APPLY'|'REJECT'>();
  useEffect(()=>{void unwrap(api.attendance.correctionEmployees()).then(setEmployees).catch(c=>notify({kind:'error',text:c instanceof Error?c.message:'従業員を読み込めませんでした。'}));},[api,notify]);
  const loadShifts=useCallback(async(id:string)=>{try{setShifts(await unwrap(api.attendance.correctionShifts(id)));}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'勤務を読み込めませんでした。'});}},[api,notify]);
  const select=async(id:string)=>{setEmployee(id);setDetail(undefined);setInput(undefined);if(id)await loadShifts(id);else setShifts([]);};
  const open=async(shiftId:string)=>{try{const data=await unwrap(api.attendance.correctionDetail(shiftId));setDetail(data);setInput({shiftId,startAt:data.effectiveClockIn,endAt:data.effectiveClockOut??Date.now(),hourlyWage:data.effectiveHourlyWage,reason:'',calculationMethod:data.calculationMethod,longShiftConfirmed:data.longShiftConfirmed});}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'訂正内容を読み込めませんでした。'});}};
  const change=(key:keyof CorrectionInput,value:CorrectionInput[keyof CorrectionInput])=>setInput(current=>current?{...current,[key]:value}:current);
  const showPreview=async(event:FormEvent)=>{event.preventDefault();if(!input)return;if(input.endAt<=input.startAt)return notify({kind:'error',text:'退勤は出勤より後の日時を入力してください。'});try{setPreview(await unwrap(api.attendance.previewCorrection(input)));}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'訂正内容を確認できませんでした。'});}};
  const apply=async()=>{if(!input)return;try{await unwrap(api.attendance.applyCorrection({...input,requestId:rid()}));notify({kind:'success',text:'出勤訂正を保存しました。履歴は保持されます。'});setPreview(undefined);setDetail(undefined);setInput(undefined);await loadShifts(employee);}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'訂正を保存できませんでした。'});setPreview(undefined);}};
  const voidShift=useCallback(async(values:{shiftId:string;adminPin:string})=>{await unwrap(api.attendance.voidShift({...values,requestId:rid()}));notify({kind:'success',text:'出勤記録を削除しました。'});setDetail(undefined);setInput(undefined);setPreview(undefined);await loadShifts(employee);},[api,employee,loadShifts,notify]);
  const CorrectionAudit=useMemo(() => ({detail:auditDetail}:{detail:CorrectionDetailDto})=><CorrectionAuditBase detail={auditDetail} onVoid={voidShift}/>,[voidShift]);
  const pending=detail?.history.find(item=>item.status==='PENDING');
  const resolve=async()=>{if(!pending||!legacyAction)return;try{await unwrap(api.attendance.resolveLegacyCorrection({correctionId:pending.id,action:legacyAction,requestId:rid()}));notify({kind:'success',text:legacyAction==='APPLY'?'旧承認待ちを反映しました。':'旧承認待ちを取り消しました。'});setLegacyAction(undefined);setDetail(undefined);setInput(undefined);await loadShifts(employee);}catch(c){notify({kind:'error',text:c instanceof Error?c.message:'旧承認待ちを解決できませんでした。'});setLegacyAction(undefined);}};
  return <><h2>出勤訂正</h2><label>従業員<select value={employee} onChange={e=>void select(e.target.value)}><option value="">選択してください</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>{!detail&&<div className="card-list correction-list">{shifts.map(shift=><article className="employee-row" key={shift.shiftId}><div><strong>{shift.workDate}・{hm(shift.effectiveClockIn)}〜{hm(shift.effectiveClockOut)}</strong><span>{shift.corrected?'訂正済み':shift.legacyPending?'旧承認待ちあり':'未訂正'}</span></div><button onClick={()=>void open(shift.shiftId)}>選択</button></article>)}</div>}{detail&&input&&<form className="stack-form correction-form" onSubmit={showPreview}><button type="button" className="back" onClick={()=>{setDetail(undefined);setInput(undefined);}}>‹ 勤務一覧へ戻る</button><h3>{detail.employeeName}さん・訂正入力</h3><CorrectionAudit detail={detail}/><label>出勤<input type="datetime-local" value={toLocalInput(input.startAt)} onChange={e=>change('startAt',new Date(e.target.value).getTime())}/></label><label>退勤<input type="datetime-local" value={toLocalInput(input.endAt)} onChange={e=>change('endAt',new Date(e.target.value).getTime())}/></label><label>訂正時給（円）<input inputMode="numeric" value={input.hourlyWage} onChange={e=>change('hourlyWage',Number(e.target.value.replace(/[^0-9０-９]/g,'').normalize('NFKC')))}/></label><label>訂正理由（任意）<textarea maxLength={240} value={input.reason??''} onChange={e=>change('reason',e.target.value)}/></label><label>計算方法<select value={input.calculationMethod} onChange={e=>change('calculationMethod',e.target.value as CalculationMethod)}><option value="HALF_HOUR">30分丸め</option><option value="ACTUAL_MINUTES">実分</option></select></label><label className="check-label"><input type="checkbox" checked={input.longShiftConfirmed} onChange={e=>change('longShiftConfirmed',e.target.checked)}/>24時間以上の勤務であることを確認しました</label>{pending&&<div className="legacy-panel"><strong>旧承認待ちがあります</strong><p>訂正を進める前に反映または取り消しを選んで解決してください。</p><div><button type="button" onClick={()=>setLegacyAction('REJECT')}>取り消す</button><button type="button" onClick={()=>setLegacyAction('APPLY')}>反映する</button></div></div>}<button className="primary" disabled={Boolean(pending)}>変更内容を確認</button></form>}{preview&&input&&<Dialog title="訂正内容を確認" closeLabel="入力へ戻る" onClose={()=>setPreview(undefined)} actions={<button className="primary" onClick={()=>void apply()}>この内容で保存</button>}><Comparison label="変更前" detail={preview.before}/><section className="preview-block"><h3>変更後</h3><p>所属日 {preview.after.workDate}</p><PayView pay={preview.after.pay}/></section></Dialog>}{legacyAction&&pending&&<Dialog title={legacyAction==='APPLY'?'旧承認待ちを反映しますか？':'旧承認待ちを取り消しますか？'} closeLabel="キャンセル" onClose={()=>setLegacyAction(undefined)} actions={<button className={legacyAction==='REJECT'?'danger-button':'primary'} onClick={()=>void resolve()}>{legacyAction==='APPLY'?'反映する':'取り消す'}</button>}><p>{legacyAction==='APPLY'?'承認待ちの訂正値を即時反映します。':'承認待ちの訂正を反映せずに解決します。'}この操作は履歴に残ります。</p></Dialog>}</>;
}
function toLocalInput(value:number){const date=new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(value-offset).toISOString().slice(0,16)}
function PayView({pay}:{pay:CorrectionDetailDto['currentPay']}){return pay?<dl className="detail-list"><div><dt>通常時間</dt><dd>{pay.regularMinutes}分</dd></div><div><dt>深夜時間</dt><dd>{pay.nightMinutes}分</dd></div><div><dt>通常分</dt><dd>{yen(pay.regularYen)}</dd></div><div><dt>深夜分</dt><dd>{yen(pay.nightYen)}</dd></div><div><dt>合計</dt><dd>{yen(pay.totalYen)}</dd></div></dl>:<p>集計対象外です。</p>}
function Comparison({label,detail}:{label:string;detail:CorrectionDetailDto}){return <section className="preview-block"><h3>{label}</h3><p>所属日 {new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo'}).format(new Date(detail.effectiveClockIn))}</p><PayView pay={detail.currentPay}/></section>}
function CorrectionAuditBase({detail,onVoid}:{detail:CorrectionDetailDto;onVoid:(values:{shiftId:string;adminPin:string})=>Promise<void>}){
  const [step,setStep]=useState<0|1|2>(0); const [pin,setPin]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const close=()=>{if(busy)return;setStep(0);setPin('');setError('');};
  const execute=async()=>{if(pin.length!==6){setError('管理者PINを6桁で入力してください。');return;}setBusy(true);setError('');try{await onVoid({shiftId:detail.shiftId,adminPin:pin});setStep(0);setPin('');}catch(cause){setError(cause instanceof Error?cause.message:'出勤記録を削除できませんでした。');}finally{setBusy(false);}};
  return <section className="correction-audit">
    <h3>元打刻と現在値</h3>
    <dl className="detail-list"><div><dt>元打刻</dt><dd>{new Date(detail.originalClockIn).toLocaleString('ja-JP')}〜{detail.originalClockOut?new Date(detail.originalClockOut).toLocaleString('ja-JP'):'勤務中'}</dd></div><div><dt>元時給</dt><dd>{yen(detail.originalHourlyWage)}</dd></div><div><dt>現在の実効値</dt><dd>{new Date(detail.effectiveClockIn).toLocaleString('ja-JP')}〜{detail.effectiveClockOut?new Date(detail.effectiveClockOut).toLocaleString('ja-JP'):'勤務中'}・{yen(detail.effectiveHourlyWage)}</dd></div></dl>
    <h3>訂正履歴</h3>
    {detail.history.length?detail.history.map(item=><article className="history-row" key={item.id}><strong>{item.status==='PENDING'?'承認待ち':item.status==='APPROVED'?'反映済み':'取り消し'}</strong><span>{new Date(item.startAt).toLocaleString('ja-JP')}〜{new Date(item.endAt).toLocaleString('ja-JP')}</span><span>時給 {yen(item.hourlyWage)}・{item.calculationMethod==='HALF_HOUR'?'30分丸め':'実分'}</span><span>理由：{item.reason||'なし'}</span><small>作成 {new Date(item.createdAt).toLocaleString('ja-JP')}／適用 {item.appliedAt?new Date(item.appliedAt).toLocaleString('ja-JP'):'—'}</small></article>):<p className="form-hint">訂正履歴はありません。</p>}
    <div className="void-shift-zone"><button type="button" className="void-shift-button" onClick={()=>setStep(1)}>この出勤記録を削除</button></div>
    {step===1&&<Dialog title="出勤記録を削除（確認 1 / 2）" closeLabel="閉じる" onClose={close} actions={<button className="danger-button" onClick={()=>{setError('');setStep(2);}}>次へ</button>}><p><strong>{detail.employeeName}さん</strong></p><p>元打刻：{new Date(detail.originalClockIn).toLocaleString('ja-JP')}〜{detail.originalClockOut?new Date(detail.originalClockOut).toLocaleString('ja-JP'):'勤務中'}</p><p>この記録は通常画面と給与集計から除外されます。元記録と削除履歴は監査用に保持されます。</p></Dialog>}
    {step===2&&<Dialog title="出勤記録を削除（確認 2 / 2）" closeLabel="戻る" onClose={()=>{if(!busy){setStep(1);setError('');}}} actions={<button className="danger-button" disabled={busy} onClick={()=>void execute()}>{busy?'削除しています…':'削除を実行'}</button>}><p className="void-warning">この記録は通常画面と給与集計へ戻せません。元記録と削除履歴だけが監査用に保持されます。</p><label>管理者PIN<input type="password" inputMode="numeric" autoComplete="current-password" maxLength={6} value={pin} onChange={event=>setPin(normalizeNumericInput(event.target.value,6))}/></label>{error&&<p className="form-error" role="alert">{error}</p>}</Dialog>}
  </section>
}
function MonthBar({ month, setMonth }: { month:string;setMonth:(value:string)=>void }) { return <div className="month-bar"><button aria-label="前の月" onClick={()=>setMonth(moveMonth(month,-1))}>‹</button><strong>{new Date(`${month}-01T00:00`).toLocaleDateString('ja-JP',{year:'numeric',month:'long'})}</strong><button aria-label="次の月" onClick={()=>setMonth(moveMonth(month,1))}>›</button></div>; }
function ErrorState({text,retry}:{text:string;retry:()=>Promise<void>}){return <div className="empty-state error" role="alert"><strong>読み込みに失敗しました</strong><p>{text}</p><button onClick={()=>void retry()}>再試行</button></div>}
